export const BOARD = {
  WIDTH: 620,
  PEG_RADIUS_RATIO: 0.15,
  PEG_BORDER_WIDTH: 2,
  PEG_GLOW_DURATION: 260,
  PEG_GLOW_BLUR: 12,
  PEG_RIPPLE_EXPAND_RATIO: 0.9,
  BALL_RADIUS_RATIO: 0.17,
  BALL_TRAIL_RADIUS_RATIO: 1.45,
  BALL_TRAIL_BLUR: 10,
  BALL_TRAIL_OPACITY: 0.5,
  PITCH_Y_RATIO: 1.05,
  TOP_OFFSET_RATIO: 0.3,
  BUCKET_ZONE_RATIO: 0.5,
  TOP_PEGS: 3,
  REPLAY_FRAMES_PER_MS: 0.03,
  REPLAY_FRAMES_PER_MS_TURBO: 0.3,
} as const;

export const PHYSICS = {
  GRAVITY_RATIO: 0.021,
  SAFETY_SPEED_RATIO: 1.5,
  BOUNCE_JITTER_RATIO: 0.12,
  RESTITUTION: 0.72,
  WALL_RESTITUTION: 0.36,
  TANGENT_RETENTION: 0.85,
  MIN_BOUNCE_SPEED_RATIO: 0.05,
  MAX_BOUNCE_HEIGHT_RATIO: 1,
  MAX_BOUNCES_PER_TIER: 3,
  SQUASH_FACTOR: 0.22,
  SQUASH_RECOVERY: 0.18,
  START_OFFSET_RATIO: 0.3,
  MAX_STEPS: 400,
  COLLISION_SUBSTEPS: 6,
} as const;

export const SOLVER = {
  MAX_ATTEMPTS: 300,
  MAX_FRAMES: 220,
  START_BIAS_RATIO: 0.55,
  START_JITTER_RATIO: 1.2,
} as const;

export const RESULT_OVERLAY_DURATION_MS = 2000;
export const RESULT_OVERLAY_DURATION_TURBO_MS = 700;

export const CSS_VAR = {
  PEG: '--plinko-peg',
  PEG_GLOW: '--plinko-peg-glow',
  BALL_FROM: '--plinko-ball-from',
  BALL_TO: '--plinko-ball-to',
  BALL_HIGHLIGHT: '--plinko-ball-highlight',
  BALL_TRAIL_FROM: '--plinko-ball-trail-from',
  BALL_TRAIL_TO: '--plinko-ball-trail-to',
} as const;
