export { ROUTES } from './routes';
export {
  BUTTON_LABELS,
  FOOTER_ABOUT_LINKS,
  SOCIAL_LINKS,
  COPYRIGHT_TEXT,
  FOOTER_HEADERS,
  FOOTER_ARIA,
  GAME_PANEL_TAB,
  type GamePanelTab,
  GAME_PANEL_LABELS,
  GAME_BALANCE,
  BET_AMOUNT_STEP,
  BET_AMOUNT_DECIMALS,
  COIN_ICON,
  GAME_POINT_ICON,
} from './constants';
