export const ROUTES = {
  HOME: '/',
  PROFILE: '/profile',
  CONNECTIONS: '/connections',
  BETS_HISTORY: '/bets-history',
  AFFILIATES: '/affiliates',
  SEED_HISTORY: '/seed-history',
  POINTSHOP: '/pointshop',
  LEADERBOARD: '/leaderboard',
  GAMES: '/games',
  REWARDS: '/rewards',
  BONUSES: '/bonuses',
  THE_WHEEL: '/the-wheel',
  BONUS_BUY_WINNERS: '/bonus-buy-winners',
  GAMES_ROULETTE: '/games/roulette',
  GAMES_KENO: '/games/keno',
  GAMES_PLINKO: '/games/plinko',
  GAMES_DICE: '/games/dice',
} as const;
